#!/bin/bash
# Copyright 2025 MongoDB Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# Ensure VERSION is provided
if [[ -z "${VERSION:-}" ]]; then
  echo "Error: VERSION environment variable must be set."
  exit 1
fi

export BRANCH="new-release/${VERSION}"
export COMMIT_MESSAGE="feat: release ${VERSION}"
export RELEASE_DIR="releases/${VERSION}"

# Git identity setup
git config --global user.name "release-bot[bot]"
git config --global user.email "456789+release-bot[bot]@users.noreply.github.com"

# Clean and prepare release directory
rm -rf "$RELEASE_DIR"
mkdir -p "$RELEASE_DIR"
cp -r deploy "$RELEASE_DIR/deploy"
cp -r bundle "$RELEASE_DIR/bundle"
cp -r helm-charts "$RELEASE_DIR/helm-charts"
cp bundle.Dockerfile "$RELEASE_DIR/bundle.Dockerfile"

# Git branch setup
git fetch origin
git checkout -f -b "$BRANCH" origin/main
git push -f origin "$BRANCH"

# Add files and sign commit
git add -f "$RELEASE_DIR"
scripts/create-signed-commit.sh

# Create draft PR
gh pr create \
  --draft \
  --base main \
  --head "$BRANCH" \
  --title "$COMMIT_MESSAGE" \
  --body "This is an autogenerated PR to prepare for the release"