name: Prepare Release Image

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  prepare-release-image:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 
        run: |
          echo "All tests passed. Preparing release image..."
