name: Promote Image

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

env:
  GHCR_REPO: ghcr.io/${{ github.repository_owner }}/mongodb-atlas-kubernetes-operator-prerelease
  DOCKER_REPO: docker.io/${{ secrets.DOCKER_USERNAME }}/mongodb-ako
  QUAY_REPO: quay.io/mongodb/mongodb-atlas-kubernetes-operator

jobs:
  fetch-e2e-image:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.event == 'push' || 
      github.event.workflow_run.event == 'schedule')
    steps:
      - name: Checkout PR commit
        uses: actions/checkout@v4
      
      # Note, we have to be careful how we retrive the image. The event that pushed 
      # the image to the ghcr.io repo was mainly a push/schedule that passed all the
      # tests. This event has access to github.ref_name. However, the workflow_run
      # event does not have access github.ref_name set up. 
      # 
      # Therefore, we need to manually specify the branch
      - id: set_tag
        uses: ./.github/actions/set-tag
        with:
          branch_name: ${{ github.event.workflow_run.head_branch }}
          commit_sha: ${{ github.event.workflow_run.head_sha }}

      - id: set_image_url
        run: |
          echo "image_url=${REPO}:${{ steps.set_tag.outputs.tag }}" >> "$GITHUB_OUTPUT"

      - name: Log in to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io \
              -u ${{ github.actor }} \
              --password-stdin

      - name: Pull unofficial image
        run: |
          docker pull ${{ steps.set_image_url.outputs.image_url }}

  promote-image:
    runs-on: ubuntu-latest
    environment: realease
    needs: [fetch-e2e-image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            
      - name: Retag for Docker Hub
        run: |
          docker tag ${GHCR_REPO}:${{ needs.fetch-e2e-image.outputs.tag }} \
                     ${DOCKER_REPO}:${{ needs.fetch-e2e-image.outputs.tag }}

      - name: Push to Docker Hub
        run: |
          docker push ${DOCKER_REPO}:${{ needs.fetch-e2e-image.outputs.tag }}

      - name: Log in to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: mongodb+mongodb_atlas_kubernetes
          password: ${{ secrets.QUAY_PASSWORD }}
