name: Promote Image

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  fetch-e2e-image:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.event == 'push' || 
      github.event.workflow_run.event == 'schedule')
    env:
      REPO: ghcr.io/${{ github.repository_owner }}/mongodb-atlas-kubernetes-operator-prerelease
    steps:
      - name: Checkout PR commit
        uses: actions/checkout@v4
      
      # Note, we have to be careful how we retrive the image. The event that pushed 
      # the image to the ghcr.io repo was mainly a push/schedule that passed all the tests. 
      # This event has access to github.ref_name. However, the workflow_run event
      # does not have access github.ref_name set up. 
      # 
      # Therefore, we manually specify the branch (github.event.workflow_run.head_branch == main)
      - id: set_tag
        uses: ./.github/actions/set-tag
        with:
          branch_name: ${{ github.head_ref || github.ref_name || github.event.workflow_run.head_branch }}
          commit_sha: ${{ github.event.workflow_run.head_sha || github.sha }}

      - id: set_image_url
        run: |
          echo "image_url=${REPO}:${{ steps.set_tag.outputs.tag }}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io \
              -u ${{ github.actor }} \
              --password-stdin

      - name: Pull image
        run: |
          echo "Pulling image: ${{ steps.set_image_url.outputs.image_url }}"
          docker pull ${{ steps.set_image_url.outputs.image_url }}

  promote-image:
    runs-on: ubuntu-latest
    needs: [fetch-e2e-image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Promote
        run: |
          echo "All tests passed. Preparing release image..."
